"""
PIPELINE ORCHESTRATOR
──────────────────────
Ties all four agents together into a single `run_pipeline()` function.

Full flow:
  1. fetch_dataset         (ingestion_agent)
  2. run_cleaning_agent    (cleaning_agent)
  3. store_dataset         (storage_agent)
  4. get_schema_for_llm   (storage_agent)
  5. run_sql_agent         (sql_agent)
  6. execute_sql           (execution_agent)
  → Returns chart-ready JSON response
"""

import os
import json
import base64
from groq import Groq

from .ingestion_agent import fetch_dataset
from .cleaning_agent import run_cleaning_agent
from .storage_agent import store_dataset, get_schema_for_llm
from .sql_agent import run_sql_agent
from .execution_agent import execute_sql
from .dashboard_agent import run_auto_dashboard_agent
from .dynamic_dashboard_agent import generate_four_dashboards_complete

# Initialize Groq client
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def run_auto_dashboard_pipeline(dataset_url: str, user_id: int) -> dict:
    print("\n" + "="*60)
    print(f"🚀 AUTO-DASHBOARD PIPELINE START | user={user_id}")
    print("="*60)

    # 1/2/3. Fetch, Clean, Store (like standard pipeline)
    print("\n[STEP 1-3] Ingesting & Storing...")
    df_raw = fetch_dataset(dataset_url)
    df_clean, cleaning_plan = run_cleaning_agent(df_raw)
    table_name = store_dataset(df_clean, user_id)
    schema, sample_csv = get_schema_for_llm(user_id)

    # 4. Agentic Generation of the 4 Dashboards
    print("\n[STEP 4] Running Auto-Dashboard Agent (LLM)...")
    json_spec = run_auto_dashboard_agent(table_name, schema, sample_csv)

    # 5. Execute SQL for all charts generated
    print("\n[STEP 5] Executing SQL for all auto-generated charts...")
    for dash in json_spec.get("dashboards", []):
        for chart in dash.get("charts", []):
            try:
                # Run the exact SQL generated by the LLM
                records = execute_sql(chart["sql_query"])
                chart["data"] = records
            except Exception as e:
                print(f"⚠️ SQL execution failed for chart {chart.get('title')}: {e}")
                chart["data"] = []
                chart["error"] = str(e)

    print("\n" + "="*60)
    print(f"✅ AUTO-DASHBOARD PIPELINE COMPLETE")
    print("="*60 + "\n")

    return json_spec

def run_pipeline(
    dataset_url: str,
    user_query: str,
    requested_charts: list[str],
    user_id: int,
) -> dict:
    """
    Orchestrate the full agentic BI pipeline.

    Parameters
    ----------
    dataset_url     : Direct CSV URL or Google Sheets share link
    user_query      : Natural language question from the user
    requested_charts: List of chart type strings (e.g., ['bar', 'line'])
    user_id         : Authenticated user's integer ID

    Returns
    -------
    A chart-ready JSON dict:
    {
        "data": [...],
        "chart_type": "bar",
        "x_axis": "region",
        "y_axis": "total_revenue",
        "title": "Revenue by Region",
        "sql_query": "SELECT ...",
        "rows_returned": 12
    }
    """

    print("\n" + "="*60)
    print(f"🚀 PIPELINE START  |  user={user_id}")
    print(f"   dataset_url : {dataset_url}")
    print(f"   query       : {user_query}")
    print(f"   charts      : {requested_charts}")
    print("="*60)

    # ── STEP 1: Ingest ────────────────────────────────────────────
    print("\n[STEP 1] Ingesting dataset...")
    df_raw = fetch_dataset(dataset_url)

    # ── STEP 2: Clean + Feature Engineering (LLM) ─────────────────
    print("\n[STEP 2] Running Cleaning Agent (LLM)...")
    df_clean, cleaning_plan = run_cleaning_agent(df_raw)

    # ── STEP 3: Store into SQLite ─────────────────────────────────
    print("\n[STEP 3] Storing cleaned dataset...")
    table_name = store_dataset(df_clean, user_id)

    # ── STEP 4: Get Schema for SQL Agent ──────────────────────────
    print("\n[STEP 4] Extracting schema for SQL Agent...")
    schema, sample_csv = get_schema_for_llm(user_id)

    # ── STEP 5: Generate SQL + Chart Mapping (LLM) ─────────────────
    print("\n[STEP 5] Running SQL Agent (LLM)...")
    sql_plan = run_sql_agent(
        table_name=table_name,
        schema=schema,
        sample_csv=sample_csv,
        user_query=user_query,
        requested_charts=requested_charts,
    )

    # ── STEP 6: Execute SQL ────────────────────────────────────────
    print("\n[STEP 6] Executing generated SQL...")
    records = execute_sql(sql_plan["sql_query"])

    # ── STEP 7: Generate Dynamic Dashboards (LLM) ─────────────────
    print("\n[STEP 7] Generating 4 dynamic dashboards based on query results...")
    try:
        dashboards_with_data = generate_four_dashboards_complete(
            user_query=user_query,
            table_schema=schema,
            sample_data=sample_csv,
            sql_results=records,
        )
        
        print(f"✅ 4 Dynamic dashboards generated")
        
    except Exception as e:
        print(f"⚠️  Dynamic dashboards generation failed: {e}")
        # Fallback to simple chart response if dashboard generation fails
        dashboards_with_data = None

    chart_map = sql_plan.get("chart_mapping", {})

    print("\n" + "="*60)
    print(f"✅ PIPELINE COMPLETE  |  {len(records)} rows returned")
    print("="*60 + "\n")

    # Return 4 dynamic dashboards if available, otherwise fallback to single chart
    if dashboards_with_data:
        return {
            "type": "dynamic_dashboards",
            "dashboards": dashboards_with_data,
            "sql_query": sql_plan["sql_query"],
            "rows_returned": len(records),
        }
    else:
        return {
            "type": "simple_chart",
            "data": records,
            "chart_type": chart_map.get("chart_type", requested_charts[0] if requested_charts else "bar"),
            "x_axis": chart_map.get("x_axis", ""),
            "y_axis": chart_map.get("y_axis", ""),
            "title": chart_map.get("title", user_query),
            "sql_query": sql_plan["sql_query"],
            "rows_returned": len(records),
        }


def generate_dashboard_summary_voice(dashboard_type: str, dashboard_data: dict, user_id: int) -> dict:
    """
    Generate an AI voice summary for a dashboard.
    Uses Groq API with text-to-speech capability.
    
    Parameters
    ----------
    dashboard_type : str - Type of dashboard (kpi, analytics, performance, insights)
    dashboard_data : dict - Dashboard data with charts, KPIs, etc.
    user_id : int - User ID for tracking
    
    Returns
    -------
    dict with audio data
    """
    print(f"\n🎙️  Generating voice summary for {dashboard_type} dashboard (user={user_id})")
    
    try:
        # Generate summary text based on dashboard data
        summary_text = _generate_summary_text(dashboard_type, dashboard_data)
        
        # Use Groq API to generate speech
        # Note: Groq has experimental text-to-speech via their API
        # For now, we'll return the text - frontend can use Web Speech API or other TTS
        
        return {
            "status": "success",
            "dashboard_type": dashboard_type,
            "summary_text": summary_text,
            "message": "Voice summary generated successfully"
        }
    except Exception as e:
        print(f"❌ Voice generation error: {e}")
        raise


def _generate_summary_text(dashboard_type: str, dashboard_data: dict) -> str:
    """
    Generate a natural language summary for the dashboard.
    """
    kpis = dashboard_data.get("kpis", [])
    charts = dashboard_data.get("charts", [])
    insights = dashboard_data.get("insights", [])
    
    # Build summary based on dashboard type
    summaries = {
        "kpi": _summarize_kpi_dashboard,
        "analytics": _summarize_analytics_dashboard,
        "performance": _summarize_performance_dashboard,
        "insights": _summarize_insights_dashboard,
    }
    
    summarizer = summaries.get(dashboard_type, _summarize_kpi_dashboard)
    return summarizer(kpis, charts, insights)


def _summarize_kpi_dashboard(kpis, charts, insights):
    """Summarize KPI dashboard."""
    text = "Here's your Key Performance Indicators dashboard summary. "
    
    if kpis:
        text += f"We have {len(kpis)} key metrics: "
        for kpi in kpis[:5]:  # First 5 KPIs
            label = kpi.get("label", "Metric")
            value = kpi.get("value", "N/A")
            change = kpi.get("change", "0%")
            text += f"{label} is {value}, with a {change} change. "
    
    if insights:
        text += "Key insights: "
        for insight in insights[:3]:
            text += f"{insight.get('text', '')} "
    
    return text


def _summarize_analytics_dashboard(kpis, charts, insights):
    """Summarize Analytics dashboard."""
    text = "Here's your Analytics dashboard overview. "
    
    if charts:
        text += f"You have {len(charts)} charts analyzing different aspects. "
        for chart in charts[:3]:
            title = chart.get("title", "Chart")
            chart_type = chart.get("type", "graph")
            text += f"{title} shows {chart_type} analysis. "
    
    if insights:
        text += "Notable findings: "
        for insight in insights[:3]:
            text += f"{insight.get('text', '')} "
    
    return text


def _summarize_performance_dashboard(kpis, charts, insights):
    """Summarize Performance dashboard."""
    text = "Here's your Performance dashboard report. "
    
    if kpis:
        text += f"Current performance metrics include {len(kpis)} key indicators. "
        for kpi in kpis[:4]:
            label = kpi.get("label", "Metric")
            value = kpi.get("value", "N/A")
            status = kpi.get("status", "stable")
            text += f"{label} is at {value} and {status}. "
    
    if insights:
        text += "Performance insights: "
        for insight in insights[:3]:
            text += f"{insight.get('text', '')} "
    
    return text


def _summarize_insights_dashboard(kpis, charts, insights):
    """Summarize Insights dashboard."""
    text = "Here's your Detailed Insights dashboard. "
    
    if insights:
        text += f"We have {len(insights)} key insights for you. "
        for insight in insights[:5]:
            text += f"{insight.get('text', '')} "
    
    if charts:
        text += f"Supported by {len(charts)} analytical visualizations. "
    
    return text
